# Generated by Django 3.2.4 on 2021-07-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='发布会名称')),
                ('address', models.CharField(max_length=256, verbose_name='发布会地点')),
                ('limits', models.IntegerField(default=100, verbose_name='发布会人数')),
                ('status', models.BooleanField(default=True, verbose_name='发布会状态')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=256, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='GuestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('is_sgin', models.BooleanField(default=False, verbose_name='签到状态')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgin.event', verbose_name='发布会')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgin.guest', verbose_name='嘉宾')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(through='sgin.GuestEvent', to='sgin.Event'),
        ),
    ]
