# NOTE: Generated By HttpRunner v3.1.5
# FROM: suite_case\add_course.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase2.login_test import TestCaseLogin as Login


class TestCaseAddCourse(HttpRunner):

    config = (
        Config("添加课程")
        .base_url("http://120.55.190.222:7080")
        .verify(False)
        .export(*["course_id", "cookie"])
    )

    teststeps = [
        Step(RunTestCase("登录").call(Login).export(*["cookie"])),
        Step(
            RunRequest("添加课程")
            .post("/api/mgr/sq_mgr/")
            .with_cookies(**{"sessionid": "${cookie}"})
            .with_data(
                {
                    "action": "add_course",
                    "data": '{"name":"初中化学","desc":"初中化学课程","display_idx":"4"}',
                }
            )
            .extract()
            .with_jmespath("body.id", "course_id")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseAddCourse().test_start()
