# NOTE: Generated By HttpRunner v3.1.5
# FROM: suite_case\update_course.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUpdateCourse(HttpRunner):

    config = (
        Config("修改课程")
        .base_url("http://120.55.190.222:7080")
        .verify(False)
        .export(*["course_id", "cookie"])
    )

    teststeps = [
        Step(
            RunRequest("修改课程")
            .put("/api/mgr/sq_mgr/")
            .with_cookies(**{"sessionid": "${cookie}"})
            .with_data(
                {
                    "action": "modify_course",
                    "id": "${course_id}",
                    "newdata": '{"name":"初中计算机","desc":"初中计算机课程","display_idx":"4"}',
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseUpdateCourse().test_start()
