# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\demo.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase.login_test import TestCaseLogin as Login


class TestCaseDemo(HttpRunner):

    config = Config("case1").base_url("http://120.55.190.222:7080").verify(False)

    teststeps = [
        Step(RunTestCase("登录").call(Login).export(*["cookie"])),
        Step(
            RunRequest("步骤二-列出课程")
            .get("/api/mgr/sq_mgr/")
            .with_params(**{"action": "list_course", "pagenum": 1, "pagesize": 20})
            .with_cookies(**{"sessionid": "${cookie}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo().test_start()
