# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase2\login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("登录")
        .base_url("http://120.55.190.222:7080")
        .verify(False)
        .export(*["cookie"])
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/api/mgr/loginReq")
            .with_data({"username": "auto", "password": "sdfsdfsdf"})
            .extract()
            .with_jmespath("cookies.sessionid", "cookie")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
