# NOTE: Generated By HttpRunner v3.1.5
# FROM: setup_teardown\update_suite.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase2.add_course_test import TestCaseAddCourse as AddCourse


class TestCaseUpdateCourse(HttpRunner):

    config = (
        Config("修改课程")
        .base_url("http://120.55.190.222:7080")
        .verify(False)
        .export(*["course_id", "cookie"])
    )

    teststeps = [
        Step(RunTestCase("添加课程").call(AddCourse).export(*["course_id", "cookie"])),
        Step(
            RunRequest("修改课程")
            .put("/api/mgr/sq_mgr/")
            .with_cookies(**{"sessionid": "${cookie}"})
            .with_data(
                {
                    "action": "modify_course",
                    "id": "${course_id}",
                    "newdata": '{"name":"初中计算机","desc":"初中计算机课程","display_idx":"4"}',
                }
            )
            .teardown_hook("${hook_teardown()}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseUpdateCourse().test_start()
