# NOTE: Generated By HttpRunner v3.1.5
# FROM: listcourse.json


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseListcourse(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/mgr/sq_mgr/")
            .get("http://120.55.190.222:7080/api/mgr/sq_mgr/")
            .with_params(**{"action": "list_course", "pagenum": "1", "pagesize": "20"})
            .with_headers(
                **{
                    "Host": "120.55.190.222:7080",
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
                    "Referer": "http://120.55.190.222:7080/mgr/ps/mgr/index.html",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "sessionid=e9a2ksxrkmgnbkxjypr93lssq96a4alo",
                }
            )
            .with_cookies(**{"sessionid": "e9a2ksxrkmgnbkxjypr93lssq96a4alo"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.retcode", 0)
            .assert_equal("body.total", 21)
        ),
    ]


if __name__ == "__main__":
    TestCaseListcourse().test_start()
